name: scopr
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.3
  firebase_core: ^2.4.1
  firebase_auth: ^4.1.5
  firebase_storage: ^11.0.6
  firebase_ui_auth: ^1.1.6
  cloud_firestore: ^4.1.0

  get: ^4.6.5
  fluttertoast: ^8.1.1
  file_picker: ^5.2.3
  intl: ^0.17.0
  datepicker_dropdown: ^0.0.7+2
  get_storage: ^2.0.3
  http: ^0.13.5
  carousel_slider: ^4.2.1
  purchases_flutter: ^4.5.3
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  persistent_bottom_nav_bar: ^5.0.2
  smooth_page_indicator: ^1.0.0+2
  image_picker: ^0.8.6
  swipe_cards: ^2.0.0+1
  easy_search_bar: ^2.4.2

 #
  flutter_chat_types: ^3.6.0
  mime: ^1.0.2
  open_filex: ^4.2.2
  path_provider: ^2.0.11
  uuid: ^3.0.6
  flutter_chat_ui: ^1.6.6
  flutter_firebase_chat_core: ^1.6.4
  faker: ^2.1.0
  toggle_switch: ^2.0.1
  flutter_login: ^4.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  rename: ^2.0.1
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
